-- MySQL Script generated by MySQL Workbench
-- Fri Oct 17 18:57:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `idCliente` INT NULL,
  `Placa` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Ano` VARCHAR(45) NULL,
  `Cor` VARCHAR(45) NULL,
  PRIMARY KEY (`idVeiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Veiculo_idVeiculo`),
  INDEX `fk_Cliente_Veiculo1_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Servico_OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Servico_OS` (
  `idOS` INT NOT NULL,
  `idVeiculo` INT NULL,
  `idEquipe` INT NULL,
  `DataEmissao` DATETIME NULL,
  `DataConclusao` DATETIME NULL,
  `ValorTotal` FLOAT NULL,
  `Status` VARCHAR(45) NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idOS`, `Veiculo_idVeiculo`),
  INDEX `fk_Ordem de Servico_OS_Veiculo1_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Servico_OS_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `NomeEquipe` VARCHAR(45) NULL,
  `Ordem de Servico_OS_idOS` INT NOT NULL,
  `Ordem de Servico_OS_Veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idEquipe`),
  INDEX `fk_Equipe_Ordem de Servico_OS1_idx` (`Ordem de Servico_OS_idOS` ASC, `Ordem de Servico_OS_Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Ordem de Servico_OS1`
    FOREIGN KEY (`Ordem de Servico_OS_idOS` , `Ordem de Servico_OS_Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Ordem de Servico_OS` (`idOS` , `Veiculo_idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `DataNascimento` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `idServico` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `ValorReferencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peca` (
  `idPeca` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `ValorUnitario` FLOAT NULL,
  PRIMARY KEY (`idPeca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe_mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe_mecanico` (
  `Equipe_idEquipe` INT NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`Equipe_idEquipe`, `Mecanico_idMecanico`),
  INDEX `fk_Equipe_has_Mecanico_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_Equipe_has_Mecanico_Equipe_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_has_Mecanico_Equipe`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_has_Mecanico_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mydb`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico/OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico/OS` (
  `Servico_idServico` INT NOT NULL,
  `Ordem de Servico_OS_idOS` INT NOT NULL,
  `ValorServico` FLOAT NULL,
  PRIMARY KEY (`Servico_idServico`, `Ordem de Servico_OS_idOS`),
  INDEX `fk_Servico_has_Ordem de Servico_OS_Ordem de Servico_OS1_idx` (`Ordem de Servico_OS_idOS` ASC) VISIBLE,
  INDEX `fk_Servico_has_Ordem de Servico_OS_Servico1_idx` (`Servico_idServico` ASC) VISIBLE,
  CONSTRAINT `fk_Servico_has_Ordem de Servico_OS_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_has_Ordem de Servico_OS_Ordem de Servico_OS1`
    FOREIGN KEY (`Ordem de Servico_OS_idOS`)
    REFERENCES `mydb`.`Ordem de Servico_OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peca/OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peca/OS` (
  `Peca_idPeca` INT NOT NULL,
  `Ordem de Servico_OS_idOS` INT NOT NULL,
  `Quantidade` INT NULL,
  `ValorTotal` FLOAT NULL,
  PRIMARY KEY (`Peca_idPeca`, `Ordem de Servico_OS_idOS`),
  INDEX `fk_Peca_has_Ordem de Servico_OS_Ordem de Servico_OS1_idx` (`Ordem de Servico_OS_idOS` ASC) VISIBLE,
  INDEX `fk_Peca_has_Ordem de Servico_OS_Peca1_idx` (`Peca_idPeca` ASC) VISIBLE,
  CONSTRAINT `fk_Peca_has_Ordem de Servico_OS_Peca1`
    FOREIGN KEY (`Peca_idPeca`)
    REFERENCES `mydb`.`Peca` (`idPeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peca_has_Ordem de Servico_OS_Ordem de Servico_OS1`
    FOREIGN KEY (`Ordem de Servico_OS_idOS`)
    REFERENCES `mydb`.`Ordem de Servico_OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
